name: fyp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  weekday_selector: ^1.1.0
  uuid: ^4.2.2
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
